package za.co.lsizani;

import java.awt.GridBagLayout;
import java.util.ArrayList;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.JRootPane;

/**
 *
 * @author LSizani
 */
public class GameWindow extends javax.swing.JFrame {

    private Dictionary dic;
    private JDialog levelQuery;
    private JComboBox levelSelector;
    private ArrayList<String> levelWords;
    private String currentWord;
    private String guess = "";
    private int MAX_GUESSES = 4;
    
    /**
     * Creates new form GameWindow
     */
    public GameWindow() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        progressDisplay = new javax.swing.JEditorPane();
        guessTextBox = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        retryButton = new javax.swing.JButton();
        index0 = new javax.swing.JTextField();
        index1 = new javax.swing.JTextField();
        index2 = new javax.swing.JTextField();
        index3 = new javax.swing.JTextField();
        index4 = new javax.swing.JTextField();
        index5 = new javax.swing.JTextField();
        index6 = new javax.swing.JTextField();
        index7 = new javax.swing.JTextField();
        index8 = new javax.swing.JTextField();
        index9 = new javax.swing.JTextField();
        index10 = new javax.swing.JTextField();
        index11 = new javax.swing.JTextField();
        index12 = new javax.swing.JTextField();
        index13 = new javax.swing.JTextField();
        index14 = new javax.swing.JTextField();
        index15 = new javax.swing.JTextField();
        index16 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        newGameMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hangman V 0.0.1");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(208, 213, 112));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        progressDisplay.setEditable(false);
        jScrollPane1.setViewportView(progressDisplay);

        guessTextBox.setEditable(false);
        guessTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                guessTextBoxKeyTyped(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        retryButton.setText("Retry");

        index0.setEditable(false);
        index0.setColumns(1);

        index1.setEditable(false);

        index2.setEditable(false);

        index3.setEditable(false);

        index4.setEditable(false);

        index5.setEditable(false);

        index6.setEditable(false);

        index7.setEditable(false);

        index8.setEditable(false);
        index8.setColumns(1);

        index9.setEditable(false);

        index10.setEditable(false);

        index11.setEditable(false);

        index12.setEditable(false);

        index13.setEditable(false);

        index14.setEditable(false);

        index15.setEditable(false);

        index16.setEditable(false);

        jMenu1.setText("File");

        newGameMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newGameMenu.setText("New Game");
        newGameMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameMenuActionPerformed(evt);
            }
        });
        jMenu1.add(newGameMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(submitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(retryButton)
                .addGap(121, 121, 121))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(index0, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(index1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(index2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(index3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(index4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(index5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(index6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(index7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(index8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(index9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(index10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(index11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(guessTextBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(index12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(index13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(index14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(index15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(index16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(index0, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(index1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(index2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(index3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(index4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(index5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(index6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(index7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(index8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(index9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(index10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(index11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(index12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(index13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(index14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(index15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(index16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(guessTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(retryButton))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newGameMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameMenuActionPerformed
        levelQuery = new JDialog(this);
        levelQuery.setLayout(new GridBagLayout());
        levelQuery.setBounds(100, 100, 200, 100);
        levelSelector = new JComboBox();
        levelSelector.setSize(200, 100);
        levelQuery.setTitle("Select Game Level");
        
        JButton newGameBtn = new JButton();
        newGameBtn.setText("Start Game");
        
        
        newGameBtn.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameBtnActionPerformed(evt);
            }
        });
        
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addElement(Level.One);
        model.addElement(Level.Two);
        model.addElement(Level.Three);
        model.addElement(Level.Four);
        model.addElement(Level.Five);
        levelSelector.setModel(model);
        
        levelQuery.add(levelSelector);
        levelQuery.add(newGameBtn);
        levelQuery.setVisible(true);
                
    }//GEN-LAST:event_newGameMenuActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitButtonActionPerformed

    private void guessTextBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_guessTextBoxKeyTyped
        guess = dic.computeGuess(evt.getKeyChar()+"", currentWord, guess);
        if(guess.equalsIgnoreCase(currentWord)){
            System.out.println(guess + " -Game Won!");
        }
        else{
           if(!guess.contains(evt.getKeyChar()+"")){
               --MAX_GUESSES;
           }else{
                          
           }
           
           if(MAX_GUESSES < 0){           
               System.out.println("Game Over - You're out of guesses. \n" + currentWord);
           }
            
        }        
        guessTextBox.setText("");
        System.out.println(MAX_GUESSES);
        System.out.println(guess + " " + evt.getKeyChar());
    }//GEN-LAST:event_guessTextBoxKeyTyped

    private void newGameBtnActionPerformed(java.awt.event.ActionEvent evt) {
        (((JRootPane)
                ((JLayeredPane)
                        ((JPanel)
                                ((JButton)
                                        evt.getSource()).getParent()).
                                getParent()).getParent()).getParent()).setVisible(false);
        try {
            dic = DictionaryLevelFactory.getDictionaryForLevel((Level)levelSelector.getSelectedItem());
            startGameWithDictionary(dic);
        } catch (InvalidLevelException ex) {
            Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
    }
    
    private void startGameWithDictionary(Dictionary dic){
        showEmptyBoxes(dic.getWordLength());
        levelWords = dic.getAllWords();        
        initializeGame();
        guessTextBox.setEditable(true);            
    }
    
    private void initializeGame() {
        int index = 0;
        currentWord = levelWords.remove(index);
        for(int i =0; i < dic.getWordLength(); ++i){
                guess += "_";
        }
    }
    
    // <editor-fold defaultstate="collapsed" desc="Show/hide Empty Boxes">
    private void showEmptyBoxes(int howMany){
        switch(howMany){
            case 6:
                index0.setVisible(false);
                index1.setVisible(false);
                index2.setVisible(false);
                index3.setVisible(false);
                index4.setVisible(false);
                index5.setVisible(false);
                index6.setVisible(true);
                index7.setVisible(true);
                index8.setVisible(true);
                index9.setVisible(true);
                index10.setVisible(true);
                index11.setVisible(true);
                index12.setVisible(false);
                index13.setVisible(false);
                index14.setVisible(false);
                index15.setVisible(false);
                index16.setVisible(false);
                break;
            case 8:
                index0.setVisible(false);
                index1.setVisible(false);
                index2.setVisible(false);
                index3.setVisible(false);
                index4.setVisible(false);
                index5.setVisible(true);
                index6.setVisible(true);
                index7.setVisible(true);
                index8.setVisible(true);
                index9.setVisible(true);
                index10.setVisible(true);
                index11.setVisible(true);
                index12.setVisible(true);
                index13.setVisible(false);
                index14.setVisible(false);
                index15.setVisible(false);
                index16.setVisible(false);
                break;
            case 10:
                index0.setVisible(false);
                index1.setVisible(false);
                index2.setVisible(false);
                index3.setVisible(false);
                index4.setVisible(true);
                index5.setVisible(true);
                index6.setVisible(true);
                index7.setVisible(true);
                index8.setVisible(true);
                index9.setVisible(true);
                index10.setVisible(true);
                index11.setVisible(true);
                index12.setVisible(true);
                index13.setVisible(true);
                index14.setVisible(false);
                index15.setVisible(false);
                index16.setVisible(false);
                break;
            case 12:
                index0.setVisible(false);
                index1.setVisible(false);
                index2.setVisible(false);
                index3.setVisible(true);
                index4.setVisible(true);
                index5.setVisible(true);
                index6.setVisible(true);
                index7.setVisible(true);
                index8.setVisible(true);
                index9.setVisible(true);
                index10.setVisible(true);
                index11.setVisible(true);
                index12.setVisible(true);
                index13.setVisible(true);
                index14.setVisible(true);
                index15.setVisible(false);
                index16.setVisible(false);
                break;
            case 14:
                index0.setVisible(false);
                index1.setVisible(false);
                index2.setVisible(true);
                index3.setVisible(true);
                index4.setVisible(true);
                index5.setVisible(true);
                index6.setVisible(true);
                index7.setVisible(true);
                index8.setVisible(true);
                index9.setVisible(true);
                index10.setVisible(true);
                index11.setVisible(true);
                index12.setVisible(true);
                index13.setVisible(true);
                index14.setVisible(true);
                index15.setVisible(true);
                index16.setVisible(false);
                break;
            case 17:
                index0.setVisible(true);
                index1.setVisible(true);
                index2.setVisible(true);
                index3.setVisible(true);
                index4.setVisible(true);
                index5.setVisible(true);
                index6.setVisible(true);
                index7.setVisible(true);
                index8.setVisible(true);
                index9.setVisible(true);
                index10.setVisible(true);
                index11.setVisible(true);
                index12.setVisible(true);
                index13.setVisible(true);
                index14.setVisible(true);
                index15.setVisible(true);
                index16.setVisible(true);
                break;    
        }
    }// </editor-fold>   
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GameWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField guessTextBox;
    private javax.swing.JTextField index0;
    private javax.swing.JTextField index1;
    private javax.swing.JTextField index10;
    private javax.swing.JTextField index11;
    private javax.swing.JTextField index12;
    private javax.swing.JTextField index13;
    private javax.swing.JTextField index14;
    private javax.swing.JTextField index15;
    private javax.swing.JTextField index16;
    private javax.swing.JTextField index2;
    private javax.swing.JTextField index3;
    private javax.swing.JTextField index4;
    private javax.swing.JTextField index5;
    private javax.swing.JTextField index6;
    private javax.swing.JTextField index7;
    private javax.swing.JTextField index8;
    private javax.swing.JTextField index9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem newGameMenu;
    private javax.swing.JEditorPane progressDisplay;
    private javax.swing.JButton retryButton;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables

    
}
